- backend/src/main/java/com/WAT/BEJURYU/BejuryuApplication.java
> [CHORE] #9 : spring set-up

- android/build.gradle.kts
- android/core/data/src/main/java/com/jaino/data/di/RepositoryModule.kt
- android/core/data/src/main/java/com/jaino/data/repository/user/UserRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/user/UserRepositoryImpl.kt
- android/core/model/src/main/java/com/jaino/model/user/Analysis.kt
- android/core/model/src/main/java/com/jaino/model/user/AnalysisSentiment.kt
- android/core/network/src/main/java/com/jaino/network/datasource/user/UserDataSource.kt
- android/core/network/src/main/java/com/jaino/network/datasource/user/UserDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/di/ApiModule.kt
- android/core/network/src/main/java/com/jaino/network/di/NetworkModule.kt
- android/core/network/src/main/java/com/jaino/network/model/user/AnalysisResponse.kt
- android/core/network/src/main/java/com/jaino/network/model/user/AnalysisSentimentResponse.kt
- android/core/network/src/main/java/com/jaino/network/remote/UserService.kt
- android/feature/setting/build.gradle.kts
- android/feature/setting/src/main/java/com/jaino/setting/SettingFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/HistoryFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/HistoryViewModel.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/adapter/UserAnalyzeAdapter.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/info/HistoryInfoFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/info/HistoryInfoViewModel.kt
- android/feature/setting/src/main/java/com/jaino/setting/profile/ProfileFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/profile/ProfileViewModel.kt
- android/feature/setting/src/main/res/layout/fragment_history.xml
- android/feature/setting/src/main/res/layout/fragment_histroy_info.xml
- android/feature/setting/src/main/res/layout/item_user_analyze.xml
- android/feature/setting/src/main/res/navigation/setting_nav.xml
- android/gradle/libs.version.toml
사용자 분석 히스토리 화면 구현 
사용자 히스토리 리스트 불러오기
리스트 반환 id 값을 통해 정보 불러오기 
화면 구현
> #14/feature

- front/.env
- front/package-lock.json
- front/package.json
- front/src/apis/authClient.js
- front/src/apis/noAuthClient.js
- front/src/components/Login/Login.jsx
- front/src/components/Login/styled.jsx
- front/src/libs/api/apiClient.js
- front/src/pages/Footer/Footer.js
apis/authClient.js 파일 보완 및 로그인 화면 ui 수정
apis/authClient.js 파일 보완 및 로그인 화면 ui 수정
카카오 토큰 받아서 쿠키에 실어 서버에 전송하고 jwt 토큰 받아와서 서비스 이용하는 코드 구현중 ..! 영차영차
> [CHORE&FEATURE]#19 : 토큰 만료 및 발급 코드 추가 및 로그인 화면 수정

- front/src/setupProxy.js
setupProxy.js파일 설정
CORS 관련 오류 방지위해 proxy 설정 해줬어용
> [FEATURE]#28: setupProxy

- front/.gitignore
.env 파일 관련 이슈
kakao key 삭제 처리 완료. 추후 다시 손 볼 예정
> chore .env 파일 ignore 처리

- front/src/App.js
- front/src/components/Header.js
- front/src/components/Login/Login.jsx
- front/src/components/Login/styled.jsx
- front/src/components/MyPage/MyPage.jsx
- front/src/components/MyPage/styled.jsx
- front/src/components/Recommend/Recommend.jsx
- front/src/components/Recommend/styled.jsx
- front/src/pages/RecommendPage.jsx
주류 추천 페이지 
주류 추천 페이지 전반적 디자인 적용 및 text 입력 틀 생성
> [FEATURE]#38: 주류추천페이지 생성

- front/.env
- front/.gitignore
- front/src/components/Login/Login.jsx
.env 파일 숨김 작업
저번에는 급해서 그냥 kakao key만 지웠었는데 이번에 제대로해서 올립니당.
> [CHORE]#39: .env파일 재작업

- front/src/components/Recommend/Recommend.jsx
- front/src/components/Recommend/styled.jsx
현재 기분 텍스트 입력 기능 구현
현재 기분 텍스트 입력 기능 구현
> [FEATURE]#39: 현재 기분 텍스트 입력 기능

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/jaino/app/navigator/AppNavigatorImpl.kt
- android/core/common/src/main/java/com/jaino/common/navigation/AppNavigator.kt
- android/core/designsystem/src/main/res/drawable/baseline_search_24.xml
- android/core/designsystem/src/main/res/drawable/border_button.xml
- android/core/designsystem/src/main/res/drawable/rounded_button_background.xml
- android/core/designsystem/src/main/res/values/strings.xml
- android/feature/analyze/src/main/java/com/jaino/analyze/AnalyzeActivity.kt
- android/feature/analyze/src/main/java/com/jaino/analyze/home/AnalyzeHomeFragment.kt
- android/feature/analyze/src/main/res/layout/dialog_choose_tools.xml
- android/feature/analyze/src/main/res/layout/fragment_analyze_home.xml
- android/feature/analyze/src/main/res/layout/fragment_analyze_text.xml
- android/feature/analyze/src/main/res/navigation/analyze_nav.xml
- android/feature/dictionary/src/main/java/com/jaino/dictionary/DictionaryActivity.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/DrinkListFragment.kt
- android/feature/dictionary/src/main/res/layout/activity_dictionary.xml
- android/feature/dictionary/src/main/res/layout/fragment_drink_list.xml
- android/feature/setting/src/main/java/com/jaino/setting/SettingFragment.kt
> #42/feature

- front/src/components/Login/Login.jsx
- front/src/components/MyPage/MyPage.jsx
- front/src/components/MyPage/styled.jsx
login.jsx 파일에 있던 로그아웃 제거 및 mypage로 이동
서버와의 통신 설정 어쩌구 나머지 작업은 페이지 전체 구현 완료 되었을때 한꺼번에 코드 추가 예정쓰
> [FEATURE]#40 : logout component mypage로 분리작업

- android/core/common/build.gradle.kts
- android/core/common/src/main/java/com/jaino/common/utils/BindingAdapter.kt
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/model/src/main/java/com/jaino/model/dictionary/DrinkData.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkListDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/datasource/user/UserDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/model/dictionary/DrinkListResponse.kt
- android/feature/analyze/src/main/res/layout/fragment_analyze_result.xml
- android/feature/analyze/src/main/res/layout/fragment_analyze_text.xml
- android/feature/auth/src/main/java/com/jaino/auth/AuthActivity.kt
- android/feature/dictionary/build.gradle.kts
- android/feature/dictionary/src/main/res/layout/item_drink_list.xml
- android/gradle/libs.version.toml
> #51/feature

- front/package-lock.json
- front/package.json
- front/src/GlobalStyles.js
- front/src/components/Recommend/PhotoUpload.jsx
- front/src/components/Recommend/Recommend.jsx
- front/src/components/Recommend/styled.jsx
createObjectURL, revokeObjectURL을 사용하여 사진 첨부 및 해당 파일 preview 기능을 구현하였음
사진 첨부 기능 추가!
그러나.. 아직 createObjectURL, revokeObjectURL 기능에 대한 이해가 완벽히 된 것은 아니라 다시 공부해보고 서버와의 통신은 어떤식으로 되는지 등등.. 알아봐야할 거 같아요
> [FEATURE]#49: 사진 첨부 및 첨부 파일 preview 기능 구현

- android/core/data/src/main/java/com/jaino/data/di/RepositoryModule.kt
- android/core/data/src/main/java/com/jaino/data/repository/dictionary/DrinksRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/dictionary/DrinksRepositoryImpl.kt
- android/core/designsystem/src/main/res/drawable/home_24.xml
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/model/src/main/java/com/jaino/model/dictionary/DrinkData.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkDataSource.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/di/NetworkModule.kt
- android/core/network/src/main/java/com/jaino/network/remote/DictionaryService.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_info/DrinkInfoFragment.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_info/DrinkInfoViewModel.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/DrinkListFragment.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/adapter/DrinkDataAdapter.kt
- android/feature/dictionary/src/main/res/layout/fragment_drink_info.xml
- android/feature/dictionary/src/main/res/layout/item_drink_list.xml
- android/feature/dictionary/src/main/res/navigation/dictionary_nav.xml
#59 주류 정보 페이지 구현 
주류 리스트에서 주류 클릭시 주류 정보 페이지로 전환
> #59/feature

- android/core/data/src/main/java/com/jaino/data/repository/dictionary/DrinksRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/dictionary/DrinksRepositoryImpl.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkListDataSource.kt
- android/core/network/src/main/java/com/jaino/network/datasource/dictionary/GetDrinkListDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/remote/DictionaryService.kt
- android/feature/analyze/src/main/res/layout/fragment_analyze_text.xml
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/DrinkListFragment.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/DrinkListViewModel.kt
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_search/DrinkSearchFragment.kt
- android/feature/dictionary/src/main/res/navigation/dictionary_nav.xml
#61 카테고리에 따라 검색 기능 구현 
search -> list 네비게이션 시 파라미터를 두개로 놓고, args state에 따라 호출하는 함수 변경
> #61/feature

- front/src/apis/authClient.js
- front/src/apis/noAuthClient.js
- front/src/components/Login/Login.jsx
- front/src/setupProxy.js
로그인 관련 통신 테스트 완료
서버와의 통신 코드 추가
> #77/feature

- front/src/apis/authClient.js
- front/src/components/Header.jsx
- front/src/components/Login/Login.jsx
> [FEATURE] #77: 쿠키관련 명령어 수정

- .idea/gradle.xml
- .idea/jarRepositories.xml
- .idea/libraries/gradle_wrapper.xml
- backend/src/main/java/com/WAT/BEJURYU/auth/service/LoginService.java
- backend/src/main/java/com/WAT/BEJURYU/controller/DrinkApiController.java
- backend/src/main/java/com/WAT/BEJURYU/controller/GlobalExceptionHandler.java
- backend/src/main/java/com/WAT/BEJURYU/dto/ReviewResponse.java
- backend/src/main/java/com/WAT/BEJURYU/dto/ReviewResponses.java
- backend/src/main/java/com/WAT/BEJURYU/dto/WriteReviewRequest.java
- backend/src/main/java/com/WAT/BEJURYU/entity/Drink.java
- backend/src/main/java/com/WAT/BEJURYU/entity/Review.java
- backend/src/main/java/com/WAT/BEJURYU/service/DrinkService.java
- backend/src/main/java/com/WAT/BEJURYU/service/ReviewService.java
- backend/src/test/java/com/WAT/BEJURYU/controller/DrinkApiControllerTest.java
> #71/feature

- .github/workflows/deploy.yml
> build: 배포 스크립트 작성

- backend/src/main/java/com/WAT/BEJURYU/entity/Drink.java
- backend/src/main/java/com/WAT/BEJURYU/entity/DrinkImage.java
Mysql DB에 주류이미지 저장을 위한 image 엔티티를 추가
> [FEATURE] #89 : drinkimage 엔티티 추가

- android/core/designsystem/src/main/res/values/strings.xml
- android/feature/analyze/src/main/java/com/jaino/analyze/input_text/AnalyzeTextFragment.kt
- android/feature/analyze/src/main/res/layout/fragment_analyze_text.xml
- android/feature/review/src/main/java/com/jaino/review/write_review/WriteReviewFragment.kt
- android/feature/review/src/main/java/com/jaino/review/write_review/WriteReviewViewModel.kt
- android/feature/review/src/main/res/layout/fragment_write_review.xml
#109 text Counter 구현하기 
현재 몇 자 적었는지 체크할 수 있음.
> #109/feature

- front/package-lock.json
- front/package.json
- front/src/App.js
- front/src/apis/authClient.js
- front/src/components/Dictionary/Dictionary.jsx
- front/src/components/Dictionary/styled.jsx
- front/src/components/Header.jsx
- front/src/components/JuryuInfo/JuruInfo.jsx
- front/src/components/JuryuInfo/styled.jsx
- front/src/components/MyPage/Logout.jsx
- front/src/components/MyPage/Nickchange.jsx
- front/src/components/MyPage/styled.jsx
- front/src/components/Recommend/Recommend.jsx
- front/src/components/Recommend/styled.jsx
사전페이지 전체적인 기능 및 ui 완료
일단 디자인은 모르겠고 구현하려했던 사전페이지 내 기능(주류 정보, 리뷰작성, 리뷰 확인 등등)은 모두 완성됨..
디자인 빨리빨리 82
> 사전페이지 전체적인 기능 및 ui 완료

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/core/common/src/main/java/com/jaino/common/extensions/LongToDateExt.kt
- android/core/data/src/main/java/com/jaino/data/repository/analysis/AnalysisRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/analysis/AnalysisRepositoryImpl.kt
- android/core/designsystem/build.gradle.kts
- android/core/network/src/main/java/com/jaino/network/datasource/analysis/AnalysisDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/model/request/analysis/AnalysisSourceRequest.kt
- android/feature/analyze/build.gradle.kts
- android/feature/analyze/src/main/java/com/jaino/analyze/input_image/AnalyzeImageFragment.kt
- android/feature/analyze/src/main/java/com/jaino/analyze/input_image/AnalyzeImageViewModel.kt
- android/feature/analyze/src/main/java/com/jaino/analyze/result/AnalyzeResultFragment.kt
- android/feature/analyze/src/main/java/com/jaino/analyze/result/ui/FeedMessage.kt
- android/gradle/libs.version.toml
#120 결과 카카오톡 로그인 링크 공유 구현 
카카오톡 링크 공유
TODO
웹 배포시 링크 연결,
플레이스토어 배포시 링크 연결
> #120/feature

- android/core/data/src/main/java/com/jaino/data/di/RepositoryModule.kt
- android/core/data/src/main/java/com/jaino/data/repository/setting/ProfileRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/setting/ProfileRepositoryImpl.kt
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/model/src/main/java/com/jaino/model/setting/Profile.kt
- android/core/network/src/main/java/com/jaino/network/datasource/setting/ProfileDataSource.kt
- android/core/network/src/main/java/com/jaino/network/datasource/setting/ProfileDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/di/ApiModule.kt
- android/core/network/src/main/java/com/jaino/network/di/NetworkModule.kt
- android/core/network/src/main/java/com/jaino/network/model/request/setting/ProfileRequest.kt
- android/core/network/src/main/java/com/jaino/network/model/response/auth/SignInResponse.kt
- android/core/network/src/main/java/com/jaino/network/remote/ProfileService.kt
- android/feature/account/src/main/java/com/jaino/account/AccountActivity.kt
- android/feature/analyze/src/main/java/com/jaino/analyze/home/HomeViewModel.kt
- android/feature/auth/src/main/java/com/jaino/auth/AuthActivity.kt
- android/feature/auth/src/main/java/com/jaino/auth/AuthViewModel.kt
- android/feature/dictionary/src/main/res/layout/item_drink_list.xml
- android/feature/setting/src/main/java/com/jaino/setting/SettingFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/SettingViewModel.kt
- android/feature/setting/src/main/java/com/jaino/setting/profile/ProfileFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/profile/ProfileViewModel.kt
- android/feature/setting/src/main/res/layout/fragment_setting.xml
#123 닉네임 불러오기 / 수정 로직 구현 
닉네임 불러오기 / 수정 가능
> #123/feature

- front/src/apis/authClient.js
- front/src/components/Dictionary/Dictionary.jsx
- front/src/components/JuryuInfo/JuruInfo.jsx
- front/src/components/MyPage/MyPage.jsx
- front/src/components/MyPage/Nickchange.jsx
- front/src/components/Recommend/PhotoUpload.jsx
- front/src/components/Recommend/Recommend.jsx
> [FEATURE CHORE etc]#124: 작업 전 중간 commit

- front/src/components/Dictionary/Dictionary.jsx
- front/src/components/Dictionary/styled.jsx
- front/src/components/MyPage/MyPage.jsx
- front/src/components/MyPage/Nickchange.jsx
- front/src/components/MyPage/styled.jsx
- front/src/components/Recommend/Recommend.jsx
> #124/feature

- front/src/App.js
- front/src/components/Header.jsx
- front/src/components/HistoryInfo/HistoryInfo.jsx
- front/src/components/Main/Main.jsx
- front/src/components/Main/styled.jsx
- front/src/components/MyPage/MyPage.jsx
- front/src/components/MyPage/styled.jsx
- front/src/components/Result/Result.jsx
- front/src/components/Result/styled.jsx
- front/src/pages/HistoryInfoPage.jsx
- front/src/pages/MainPage.jsx
> #134/chore

- android/core/data/src/main/java/com/jaino/data/repository/rank/RankRepository.kt
- android/core/data/src/main/java/com/jaino/data/repository/rank/RankRepositoryImpl.kt
- android/core/designsystem/src/main/res/drawable/rounded_background.xml
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/model/src/main/java/com/jaino/model/rank/Rank.kt
- android/core/network/src/main/java/com/jaino/network/datasource/rank/RankDataSource.kt
- android/core/network/src/main/java/com/jaino/network/datasource/rank/RankDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/model/response/rank/RankResponse.kt
- android/core/network/src/main/java/com/jaino/network/remote/RankService.kt
- android/feature/analysis/src/main/java/com/jaino/analysis/home/HomeViewModel.kt
- android/feature/analysis/src/main/java/com/jaino/analysis/home/adapter/HomeRankAdapter.kt
- android/feature/analysis/src/main/res/layout/fragment_home.xml
- android/feature/analysis/src/main/res/layout/item_rank.xml
- android/feature/dictionary/src/main/res/layout/item_drink_list.xml
#119 rank 모델 구현 및 홈 화면 변경 
홈 화면의 랭킹에서 평점과 리뷰의 수를 확인 가능.
> #119/feature

- android/core/designsystem/src/main/res/values/strings.xml
- android/feature/analysis/src/main/res/layout/fragment_image_input.xml
- android/feature/dictionary/src/main/java/com/jaino/dictionary/drink_list/DrinkListFragment.kt
- android/feature/dictionary/src/main/res/layout/fragment_drink_list.xml
- android/feature/review/src/main/java/com/jaino/review/review_list/ReviewListFragment.kt
- android/feature/review/src/main/res/layout/fragment_review_list.xml
#140 빈 리스트 처리 
검색 결과가 없을 경우, 다시 검색 결과 혹은 리뷰 작성페이지로 전환되도록 구현
> #140/feature

- android/core/common/src/main/java/com/jaino/common/widget/ErrorDialog.kt
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/network/src/main/java/com/jaino/network/remote/ReviewService.kt
- android/feature/analysis/src/main/res/layout/fragment_image_input.xml
- android/feature/analysis/src/main/res/layout/fragment_text_input.xml
- android/feature/home/src/main/res/layout/fragment_home.xml
- android/feature/review/src/main/java/com/jaino/review/review_input/ReviewInputFragment.kt
- android/feature/review/src/main/java/com/jaino/review/review_input/ReviewInputViewModel.kt
- android/feature/review/src/main/res/layout/fragment_review_input.xml
- android/feature/review/src/main/res/layout/fragment_review_list.xml
#96 이용 tip 및 리뷰 주류 정보 추가 
감정 입력시 tip 확인, 주류 리뷰 작성시 현재 주류 정보 볼 수 있음.
> #96/feature

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/jaino/app/BeJuRyuApplication.kt
- android/core/designsystem/src/main/res/values-night/themes.xml
- android/feature/home/build.gradle.kts
- android/feature/home/src/main/java/com/jaino/home/HomeFragment.kt
- android/gradle/libs.version.toml
#143 다크모드, 가로 모드 제한 
홈 ui에서 status bar purple로 설정, 세로모드만 지원
> #143/feature

- android/core/common/src/main/java/com/jaino/common/constant/SentimentConst.kt
- android/core/common/src/main/java/com/jaino/common/extensions/SentimentExt.kt
- android/core/designsystem/src/main/res/values/strings.xml
- android/core/model/src/main/java/com/jaino/model/analysis/SentimentAnalysis.kt
- android/core/model/src/main/java/com/jaino/model/dictionary/Drink.kt
- android/core/network/src/main/java/com/jaino/network/datasource/analysis/AnalysisDataSourceImpl.kt
- android/core/network/src/main/java/com/jaino/network/model/response/analysis/AnalysisHistoryResponse.kt
- android/core/network/src/main/java/com/jaino/network/model/response/analysis/AnalysisIdResponse.kt
- android/core/network/src/main/java/com/jaino/network/model/response/analysis/SentimentAnalysisResponse.kt
- android/core/network/src/main/java/com/jaino/network/model/response/dictionary/DrinkInfoResponse.kt
- android/core/network/src/main/java/com/jaino/network/model/response/review/DrinkReviewResponse.kt
- android/core/network/src/main/java/com/jaino/network/remote/AnalysisService.kt
- android/feature/analysis/src/main/java/com/jaino/analysis/image_input/ImageInputFragment.kt
- android/feature/analysis/src/main/java/com/jaino/analysis/result/ResultFragment.kt
- android/feature/analysis/src/main/java/com/jaino/analysis/result/ResultViewModel.kt
- android/feature/analysis/src/main/res/layout/fragment_result.xml
- android/feature/analysis/src/main/res/navigation/analysis_nav.xml
- android/feature/dictionary/src/main/res/layout/fragment_drink_info.xml
- android/feature/dictionary/src/main/res/layout/fragment_drink_search.xml
- android/feature/dictionary/src/main/res/layout/item_drink_list.xml
- android/feature/home/src/main/res/layout/fragment_home.xml
- android/feature/review/src/main/res/layout/fragment_review_input.xml
- android/feature/review/src/main/res/layout/item_review.xml
- android/feature/setting/src/main/java/com/jaino/setting/history/HistoryFragment.kt
- android/feature/setting/src/main/java/com/jaino/setting/history/adapter/AnalysisHistoryAdapter.kt
- android/feature/setting/src/main/res/layout/fragment_profile.xml
- android/feature/setting/src/main/res/layout/item_user_analyze.xml
#146 결과 페이지 ui 수정(사용자 입력 추가) dto, model 수정
> #146/feature
